### ISSUE TITLE
Correct Link in Admin Section OCv.2.2

### ISSUE THREAD

**Issue by IP-CAM** [opencarthelp/vqmod_manager#1]
IN:
vqmm_menu_shortcut.xml
<id>VQMod Manager Menu Shortcut</id>
<file name="admin/controller/common/menu.php">

CHANGE THIS LINE:
$data['zone'] = $this->url->link('localisation/zone', 'token=' . $this->session->data['token'], 'SSL');

TO THIS:
$data['zone'] = $this->url->link('localisation/zone', 'token=' . $this->session->data['token'], true);

to make it work, linked correctly, in OC v.2.2 !

Ernie
openshop.li

**Comment by opencarthelp** [comment]
VQMM isn't compatible with OpenCart 2.x.
